version : 0.2

phases:
 build:
   commands:
     - echo entered the build phase...
     - mvn clean install -DskipTests
   post build:
    commands:
     - echo Build complete successfully
   artifacts:
    files: 
     - target/drug-service.jar
    discard-paths: yes       
